### ISSUE TITLE
Not working in UIPageViewController

### ISSUE THREAD

**Issue by praveenkumar56060** [ipedro/PAGestureAssistant#8]
Hi Ipedro,

I'm using [CarbonKit](https://github.com/ermalkaleci/CarbonKit)'s [`CarbonTabSwipeNavigation`](https://github.com/ermalkaleci/CarbonTabSwipeNavigation/raw/master/Resources/CarbonTabSwipeNavigation.gif) in my application.

`PAGestureAssistant` works fine on other viewControllers where its not working on when using this `CarbonTabSwipeNavigation` 

For, your reference i have attached the sample project below. 
[CarbonKit-master.zip](https://github.com/ipedro/PAGestureAssistant/files/680615/CarbonKit-master.zip) I have included `PAGestureAssistant` in this project. Please, build & run `CarbonKitExample1` project.

# Note:
I am showing `PAGestureAssistantSwipeDirectonDown` in `ViewControllerTwo`

**Comment by ipedro** [comment]
Hey, i looked at the project and found a workaround.

You can copy the files below to your project and it will work.

[PAGestureAssistant_praveenkumar56060.zip](https://github.com/ipedro/PAGestureAssistant/files/686038/PAGestureAssistant_praveenkumar56060.zip)


It's an interesting issue, but since this is an issue with a custom pod, I won't push an update to the repo until I fully understand what's going on beneath the hood, i'll have to test it out first.


**Just be on the lookout for any strange behaviors, ok?**


Good luck!

**Comment by praveenkumar56060** [comment]
No strange behaviours, but no changes. Still it remains the same.

**Comment by ipedro** [comment]
Did you download the zip?

![simulator screen shot 6 jan 2017 19 04 16](https://cloud.githubusercontent.com/assets/380338/21732903/ff3de984-d442-11e6-8764-902c395be2f7.png)
